In [1]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

1)

Yes, there is a difference in the data types of the variables 'list_' and 'array_list'. The variable 'list_' is a Python list, while 'array_list' is a NumPy array.

In [2]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


2)

In [3]:
# Print data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

print()

# Print data type of each element in array_list
print("Data type of each element in array_list:")
for element in array_list:
    print(type(element))

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


3)

In [4]:
array_list = np.array(object = list_, dtype = int)

Yes, there will be a difference in the data types of the elements present in both the 'list_' and 'array_list' variables after the modification 'array_list = np.array(object=list_, dtype=int)'. The 'dtype=int' argument specifies that the elements in 'array_list' should be of integer data type.

In [5]:
# Print data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

print()

# Print data type of each element in array_list
print("Data type of each element in array_list:")
for element in array_list:
    print(type(element))

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [6]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

4)

In [7]:
# (i) Finding the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# (ii) Finding the size of num_array
size = num_array.size
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


5)

In [8]:
import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


6)

In [10]:
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
